openapi: 3.0.3
info:
  title: Delivery Specification
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
tags:
  - name: Order
  - name: Status
  - name: Admin
paths:
  /order:
    get:
      summary: Retrieve a list of all orders
      tags:
        - Order
      description: return a list of order objects
      responses:
        '200':
          description: Successful response, order received
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: Unsuccessful, orders cannot be retrieved because of bad request
        '404':
          description: Unsuccessful, no orders were found

  /order/[orderId]/rating:
    put:
      tags:
        - Order
      summary: Change the rating number and comment
      description: Update both of the orders ratings
      parameters:
        - in: path
          name: orderId
          schema:
            type: number
            format: int64
          required: true
          description: Id of the order to update rating
      requestBody:
        description: Order object where status, ratingNumber and ratingComment are updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '204':
          description: Successful update of status to accepted
        '400':
          description: Invalid arguments
        '404':
          description: Order not found
        '401':
          description: Unauthorized

  /status/[orderId]/accepted:
    put:
      tags:
        - Status
      summary: Change the order status from pending to accepted
      description: Update the order status to accepted
      parameters:
        - in: path
          name: orderId
          schema:
            type: number
            format: int64
          required: true
          description: Id of the order to change status
      requestBody:
        description: Order object where status is updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '204':
          description: Successful update of status to accepted
        '400':
          description: Invalid arguments
        '404':
          description: Order not found
        '401':
          description: Unauthorized

  /status/[orderId]/preparing:
    put:
      tags:
        - Status
      summary: Change the order status from accepted to preparing
      description: Update the order status to preparing
      parameters:
        - in: path
          name: orderId
          schema:
            type: number
            format: int64
          required: true
          description: Id of order to change status
      requestBody:
        description: Order object where status and prepTime are updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '204':
          description: Successful update of status to preparing
        '400':
          description: Invalid arguments
        '404':
          description: Order not found
        '401':
          description: Unauthorized

  /status/[orderId]/intransit:
    put:
      tags:
        - Status
      summary: Change the order status from accepted to in-transit
      description: Update the order status to in-transit
      parameters:
        - in: path
          name: orderId
          schema:
            type: number
            format: int64
          required: true
          description: Id of order to change status
      requestBody:
        description: Order object where status is updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '204':
          description: Successful update of status to in-transit
        '400':
          description: Invalid arguments
        '404':
          description: Order not found
        '401':
          description: Unauthorized


components:
  schemas:
    Order:
      type: object
      properties:
        status:
          type: string
          enum:
            - pending
            - accepted
            - rejected
            - preparing
            - given to courier
            - on-transit
            - delivered
        id:
          type: number
          format: int64
        deliveryDestination:
          $ref: '#/components/schemas/Location'
        customerId:
          type: number
          format: int64
          example: 66
        vendorId:
          type: number
          format: int64
          example: 77
        courierId:
          type: number
          format: int64
          example: 88
        ratingNumber:
          type: integer
          example: 5
        ratingComment:
          type: string
        orderTime:
          type: string
          format: date-time
          example: 2023-11-28T15:30:00Z
          description: the time the order was made
        prepTime:
          type: string
          format: time
          description: the time it takes to prepare the order in format "HH:MM:SS"
          example: '01:30:00'
        expectedDeliveryTime:
          type: string
          format: date-time
          description: the time the order will be planned to be delivered
        ActualDeliveryTime:
          type: string
          format: date-time
          description: the time the order actually is delivered
    User:
      properties:
        id:
          type: number
          format: int64
          example: 66
    Vendor:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
      properties:
        radius:
          type: number
          format: double
        location:
          $ref: '#/components/schemas/Location'
        hasCouriers:
          description: to indicate if a vendor has specific couriers that are assigned to them, and can only take requests from them
          type: boolean
        independentOrders:
          type: array
          description: a queue of all the ids of the independent orders
          items:
            type: number
            format: int64
    Customer:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
    Courier:
      allOf:
        - $ref: '#/components/schemas/User'
        - type: object
      properties:
        currentLocation:
          $ref: '#/components/schemas/Location'
        bossId:
          type: number
          format: int64
          example: 666
    DeliveryException:
      properties:
        orderId:
          type: number
          format: int64
          description: the id of the order that the exception happened on
        message:
          type: string
          description: explanation of what went wrong with the order
          example: "Order was not delivered"
    LateDelivery:
      allOf:
        - $ref: '#/components/schemas/DeliveryException'
    NotDelivered:
      allOf:
        - $ref: '#/components/schemas/DeliveryException'
    Rejected:
      allOf:
        - $ref: '#/components/schemas/DeliveryException'
    Location:
      type: object
      properties:
        latitude:
          type: number
          format: float
          example: 23.92488
        longitude:
          type: number
          format: float
          example: 74.7099
